### ISSUE TITLE
Environment not checked for run_in_production config

### ISSUE THREAD

**Issue by abdurrahmanriyad** [abdurrahmanriyad/writeup#1]

**Comment by Rafatlne** [comment]
Are you trying to say that when anyone trying to grab `run_in_production` config key by `$value = config('writeup.run_in_production')`, this gave null or error?

**Comment by abdurrahmanriyad** [comment]
@Rafatlne No.
The existing code doesn't check laravel app environment (config('app.env')) if it is in production or not.

**Comment by Rafatlne** [comment]
@abdurrahmanriyad Ok. I am playing with this package right now. Trying to recreate what have you described.  If i successfully solved the issue then i will open a PR.
